name: Build with Memory Leak Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      TEST_MAPSCRIPT_PYTHON: 'true'
      TEST_MAPSCRIPT_PHP: 'true'
      RUN_MSAUTOTESTS: 'true'
      RUN_COVERALLS: 'false'
      WITH_ASAN: 'true'

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v3

      - name: Build
        run: docker run -e WORK_DIR="$PWD" -v $PWD:$PWD ubuntu:20.04 $PWD/.github/workflows/start.sh
